### ISSUE TITLE
Metrics hawkular screens don't work.  Graphs don't generate. 

### ISSUE THREAD

**Issue by alberttwong** [openshift/roadshow#13]
We need to put into docs that they need to accept the self signed ssl cert in their browser.  

For example....
 https://metrics.apps.newport.openshift3roadshow.com/

**Comment by gshipley** [comment]
In order for metrics to work, you need to accept the security cert in the infra project first.

**Comment by alberttwong** [comment]
@gshipley so I accepted it but there are no data in the graphs.

**Comment by alberttwong** [comment]
Related? https://github.com/2015-Middleware-Keynote/demo-ansible/issues/146

**Comment by kenthua** [comment]
I get the graphs, only the first 2 minutes, but only for pods deployed to env=infra

https://github.com/2015-Middleware-Keynote/demo-ansible/issues/146
https://github.com/2015-Middleware-Keynote/demo-ansible/issues/147
